package model;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
//Author: rafdam
//Math model calculating potential and electrical force generated by stationary charges
import java.util.ArrayList;
import java.util.Collections;


import gui.StationaryQTable;

public class ChargesPotential extends ChargesList {
	/**
	 * 
	 */
	static double electricForceX = 0; //derivative dPotential/dx
	static double electricForceY = 0; //derivative dPotential/dy
	static double electricForceZ = 0; //derivative dPotential/dz
	double Potential = 0; //Potential generated by stationary charges in test point
	private static final long serialVersionUID = 1L;
	double k = 0;
	double xMotionValue = 0; //Moved test x value by stationaryCharge x value
	double yMotionValue = 0; //Moved test y value by stationaryCharge y value
	double zMotionValue = 0; //Moved test z value by stationaryCharge z value
	double testCordX = 0; //Coords of testPoint in potential
	double testCordY = 0;
	double testCordZ = 0;
	
	
	public double getElectricForceX(){
		return electricForceX;
	}
	
	public double getElectricForceY(){
		return electricForceY;
	}
	
	public double getElectricForceZ(){
		return electricForceZ;
	}
	

	public double getPotential(){
		return Potential;
	}
	
	public double getTestX(){
		return testCordX;
	}
	
	public double getTestY(){
		return testCordY;
	}
	
	public double getTestZ(){
		return testCordZ;
	}
	
	
	
	
	
	
	public ChargesPotential (ArrayList<StationaryCharge> l, TestPoint w){ //Counting Potential and electric Force in given TestPoint
		
	
	k=9*Math.pow(10, 9);
	
	testCordX = w.getTestXCord();
	testCordY = w.getTestYCord();
	testCordZ = w.getTestZCord();
	
	
	for (int ii=0; ii<l.size(); ii++){
		
	xMotionValue = l.get(ii).getX() - w.getTestXCord();
	yMotionValue = l.get(ii).getY() - w.getTestYCord();
	zMotionValue = l.get(ii).getZ() - w.getTestZCord();
	Potential += (k * l.get(ii).getValue()) / (Math.sqrt(Math.pow(yMotionValue,2) + Math.pow(xMotionValue,2) + Math.pow(zMotionValue,2)));
	
	}
	
	
	double deltaElectricForceX = 0; //Potential(x+ultraSmallH,y,z)
	double deltaElectricForceY = 0; //Potential(x,y+ultraSmallH,z)
	double deltaElectricForceZ = 0; //Potential(x,y,z+ultraSmallH)
	
	
	double ultraSmallH = 0.001; //Small constant to derivative Potential
		for (int jj = 0; jj < l.size(); jj++){
			xMotionValue = -l.get(jj).getX() + w.getTestXCord();
			yMotionValue = -l.get(jj).getY() + w.getTestYCord();
			zMotionValue = -l.get(jj).getZ() + w.getTestZCord();
				
				deltaElectricForceX += (k * l.get(jj).getValue()) / (Math.sqrt(Math.pow(yMotionValue,2) + Math.pow(xMotionValue + ultraSmallH,2) + Math.pow(xMotionValue,2)));
				deltaElectricForceY += (k * l.get(jj).getValue()) / (Math.sqrt(Math.pow(yMotionValue + ultraSmallH,2) + Math.pow(xMotionValue,2) + Math.pow(yMotionValue,2)));
				deltaElectricForceZ += (k * l.get(jj).getValue()) / (Math.sqrt(Math.pow(yMotionValue,2) + Math.pow(xMotionValue,2) + Math.pow(zMotionValue + ultraSmallH,2)));
		} 
 		electricForceX=(deltaElectricForceX-Potential)/ultraSmallH;
		electricForceY=(deltaElectricForceY-Potential)/ultraSmallH;
		electricForceZ=(deltaElectricForceZ-Potential)/ultraSmallH;
		
	
	}

	public void draw(Graphics g) {
		try{
		Color PotColor = new Color(150, 200, (int)(4*Potential/(Math.pow(10, -15) * 255)));
		g.setColor(PotColor);
		
		}
		catch(IllegalArgumentException e){
			g.setColor(Color.RED);
		}
		g.fillOval((int)testCordX-1, (int)testCordY-1, 2, 2);
		
	}
	
	
	/////////////////////////////////////////////////////////////////////////////////////////////////
	/*Dimension screenSize;
	double a, b;
	PotentialList heatmap;
	ArrayList<Double> potentialValue;
	double maxValue = 0;
	double changeColor = 0;
	
	
	public void HeatMap(ChargesList ChL){
		screenSize = Toolkit.getDefaultToolkit().getScreenSize();	
		double x = 0.85 * screenSize.height;
		double y =0.85 * screenSize.height;	
		
		
		
		heatmap = new PotentialList();
		potentialValue = new ArrayList<Double>();
		
		for(int kk = 0; kk < x ; kk++){
			for ( int ww = 0; ww < y ; ww++){
				TestPoint testP = new TestPoint(kk,ww,0);
				ChargesPotential ch = new ChargesPotential(ChL, testP);
				heatmap.add(ch);
				potentialValue.add(ch.getPotential());
				maxValue = Collections.max(potentialValue);
				System.out.println(maxValue);
				
			}
		}	
	}
	
	public double getMaxValue(){
		return maxValue;
	}
	
	public ArrayList<ChargesPotential> getHeatMap(){
		return heatmap;
	}
	
	public void draw(Graphics g) {
		Color PotColor = new Color(255,255,255);
		g.setColor(PotColor);
		g.fillOval( (int)testCordX, (int)testCordY, 2, 2);
		
			
		
		}
		*/
	
	
}
	
	
	


